import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
	name: "DepsBug",
	projects: [
		"Modules/**",
	],
	schemes: [],
	additionalFiles: [
		"Workspace.swift",
		"Tuist/**/*.swift"
	],
	generationOptions: .options(
		enableAutomaticXcodeSchemes: false,
		autogeneratedWorkspaceSchemes: .disabled
	)
)
